project:
  type: book
  output-dir: docs

book:
  title: "DU-RCC"
  reader-mode: true
  
  page-footer:
    left: |
      Adapted heavily from R for Data Science (2e) by Hadley Wickham, Mine
      Çetinkaya-Rundel, and Garrett Grolemund.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: '/resources/logo.png'
  site-url: https://rcalinjageman.github.io/r_crash_course/
  repo-url: https://github.com/rcalinjageman/r_crash_course
  repo-branch: meain
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    
    - getting_started.qmd
    
    - part: day_1.qmd
      chapters:
        - day_1_intro.qmd
        - day_1_whole_game.qmd
        - day_1_first_graph.qmd
        - day_1_r_basics.qmd
        - day_1_assignments.qmd
    - part: day_2.qmd
      chapters: 
        - day_2_layers.qmd
        - day_2_exploring.qmd
        - day_2_communication.qmd
    - part: day_3.qmd
      chapters: 
        - day_3_more.qmd
    - part: day_4.qmd
      chapters:
        - day_4_more.qmd
    - part: day_5.qmd
      chapters:
        - day_5_more.qmd
    
 
format:
  html:
    theme:
      - morph
      - r4ds.scss
    code-link: true
    callout-appearance: simple

editor: visual